name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Copy files to VPS
        run: |
          rsync -avz --exclude 'venv' --exclude '__pycache__' . ${{ secrets.VPS_IP }}:/var/www/Project-nexus-job-board-api/job_board_api

      - name: Set up and activate virtual environment, install dependencies, and migrate database
        run: |
          ssh ${{ secrets.VPS_IP }} '
          cd /var/www/Project-nexus-job-board-api &&
          source venv/bin/activate &&
          cd job_board_api &&
          pip install -r requirements.txt &&
          python manage.py migrate &&
          python manage.py collectstatic --no-input
          '

      - name: Restart Gunicorn
        run: |
          ssh ${{ secrets.VPS_IP }} 'systemctl restart gunicorn'
